# Generated by Django 4.0.4 on 2022-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descriptions',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
